CREATE TABLE Profiles (rowID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, WatchName NVARCHAR(65) NOT NULL, WatchStyle INTEGER NOT NULL, ProfileActive INTEGER NOT NULL);

CREATE TABLE Workouts (rowID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, WorkoutType INTEGER NOT NULL, WorkoutScheduledRepeats INTEGER NOT NULL, WorkoutTotalLaps INTEGER NOT NULL, WorkoutDescription NVARCHAR(65) NOT NULL, WorkoutDate DOUBLE NOT NULL, WorkoutDuration DOUBLE NOT NULL, WatchID INTEGER NOT NULL, isDeleted INTEGER DEFAULT 0, FOREIGN KEY (WatchID) REFERENCES Profiles (rowID));

CREATE TABLE WorkoutLaps (rowID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, LapTime DOUBLE NOT NULL, LapTypeID INTEGER NOT NULL, WorkoutID INTEGER NOT NULL, FOREIGN KEY (WorkoutID) REFERENCES Workouts (rowID));

CREATE TABLE WorkoutUploads(rowID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, UploadSite INTEGER NOT NULL, UploadTime DOUBLE NOT NULL, WorkoutID INTEGER NOT NULL, FOREIGN KEY (WorkoutID) REFERENCES Workouts (rowID));

CREATE TABLE CalendarEventAlarms (rowID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, EventKey NVARCHAR(256) NOT NULL, EventDate DOUBLE NOT NULL, AlarmID INTEGER NOT NULL);

CREATE TABLE ExcludedCalendarEvents (rowID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, EventKey NVARCHAR(256) NOT NULL, EventDate DOUBLE NOT NULL);


CREATE TABLE M328_Goals (rowID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, calories INTEGER, distance INTEGER,steps INTEGER, sleepTime INTEGER, type INTEGER);
